# Definição da Gramática

# Lexer

<digit> ::= ['0'-'9']
<char>  ::= ['a-zA-Z']
<int>   ::= <digit>*
<id>    ::= ('_' | <char>)(<char> | <digit>)* 
<newline> ::= '\n'
<whitespace> ::= '\t' | ' '
<binop> ::= '+' | '-' | '/' | '*'
<booleanbop> ::= '>' | '>=' | '=' | '!=' | '<' | '<='

# Parser

<program> ::= <statements> 

<statements> ::= (<statement> | <function_def>)*

<type> ::= <int> | <id>

<statement> ::= <statement>*
              | 'if' '(' <boolean_expression> ')' 'then' 
			    	'{' <statement> '}'
				'else'
					'{' <statement> '}'
			  | 'foreach' <id> 'in' <int> '..' <int> 'do' '{' <statement> '}'
			  | 'print' '(' <expression> ')' ';'
			  | <id> ':=' <expression> ';'
			  | <id> '[' <expression> ']' ':=' <expression> ';'
			  | 'var' <id> ':' <int> '=' <expression> ';'

<expression> ::= <lparen> <expression> <rparen>
               | <expression> <binop> <expression>
               | <expression> <lbracket> <expression> <rbracket>
			   | <int>
			   | <id>

<boolean_expression> ::= '('<expression> <booleanop> <expression> ')'
                       |  <expression> <booleanop> <expression>
					   | '!' <boolean_expression>

<argument_list> ::= (<id> ':' <type>)*
<function_def> ::= 'function' <id> '(' <argument_list> ')' '{' <statement> '}'
